module_scum = "Scum"

msg_scum_state_table = "It is %s's turn. Cards on table: %s."
msg_scum_state_fresh = "It is %s's turn, who may come out fresh."

#########
# Cards #
#########
mt_scum_cards = "Your cards"
md_scum_cards = "Show your cards in the current scum game."
msg_scum_your_cards = "Your cards: %s"

########
# Init #
########
mt_scum_init = "Init Game"
md_scum_init = "Initiate a game of scum."
err_scum_running = "A game of scum is already running."
msg_scum_inited = "A game of scum has been initiated and you joined it. Others may type $scum.join to."

########
# Join #
########
mt_scum_join = "Join the Scum"
md_scum_join = "Join a freshly inited game of scum."
err_scum_no_game = "There is no scum game initiated. Type $scum.init to do so."
err_scum_already_started = "There is already a game running here."
err_scum_already_in_game = "You are already in the game."
err_game_full = "The game is full. Type $scum.start now."
msg_scum_joined = "You joined the scum."

########
# Play #
########
mt_scum_play = "Play cards"
md_scum_play = "Make a move in your current scum game."
err_scum_player_not_in_game = "You are not in this game."
err_scum_not_started = "There is no scum game running."
err_scum_not_your_turn = "It is not your turn."
err_scum_need_same_cards = "You need to play the same type of cards."
err_scum_need_amt_cards = "You need to play the same number of cards."
err_scum_not_right_cards = "You do not have the right cards."
err_scum_need_higher_cards = "You need to play higher cards than %s."
msg_scum_wins_round = "%s plays %s and wins this round. %s"
msg_scum_played_cards_finished = "%s plays %s and finishes with rank %s (%d points). %s"
msg_scum_played_cards = "%s plays %s and has %d cards left. %s"
msg_scum_all_passed = "%s passes. %s wins this round. %s"
msg_scum_passed = "%s passes. %s"
msg_scum_game_over = "The game is over."
msg_scum_game_over_player = "%s got place %d (%d Points). Cards: %s"

#########
# Reset #
#########
mt_scum_reset = "Reset Scum Game"
md_scum_reset = "Cancel the current Scum Game."
err_scum_reset_timeout = "Please wait %s and try again to reset the game."
msg_scum_reset = "The running scum game has been aborted."

#########
# Start #
#########
mt_scum_start = "Start Scum Game"
md_scum_start = "Start the scum game with currently joined players."
err_at_least_2_players = "There have to be at least 2 players."
msg_scum_started = "The game has started with %s. %s"
